using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace SqlRepoAnalyzer.Core.Phase3;

/// <summary>
/// Builds a DBA-readable Markdown report from <see cref="Phase3PlansReport"/>.
/// Canonical data remains <c>plans.json</c>; this file is for Confluence/Git/email review.
/// </summary>
public static class Phase3PlansMarkdownFormatter
{
    /// <summary>Renders UTF-16 Markdown text.</summary>
    public static string Format(Phase3PlansReport report)
    {
        var sb = new StringBuilder(capacity: 24_576);
        Emit(sb, report);
        return sb.ToString();
    }

    /// <summary>Writes UTF-8 without BOM, creating parent directories if needed.</summary>
    public static void WriteUtf8File(string path, Phase3PlansReport report)
    {
        var dir = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(path, Format(report), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    private static void Emit(StringBuilder sb, Phase3PlansReport report)
    {
        sb.AppendLine("# SQL optimization plan — Phase 3 (catalog / DMV)");
        sb.AppendLine();
        sb.AppendLine("Scanned queries were checked against **live database metadata** (referenced tables only). ");
        sb.AppendLine("Machine-readable output for automation and dashboards: **`plans.json`**.");
        sb.AppendLine();

        sb.AppendLine("---");
        sb.AppendLine();

        sb.AppendLine("## How DBAs should read this");
        sb.AppendLine();
        sb.AppendLine("- Items under **Action items** are **FAIL** / **WARN** findings — prioritize review or backlog.");
        sb.AppendLine("- **PASS** / informational rows mean this rule reported no issue *for this run*, not a performance guarantee.");
        sb.AppendLine("- DMV-based rules (stats freshness, unused indexes) **reset after service restart** — treat zeros as advisory.");
        sb.AppendLine("- Evidence blocks are excerpts; validate scripts and names on your environment before deploying.");
        sb.AppendLine();

        EmitRunSummary(sb, report);

        EmitRulesAtAGlance(sb, report);

        sb.AppendLine("## Queries and fingerprints");
        sb.AppendLine();
        sb.AppendLine("| Query ID | Fingerprint (SHA-256 hex) |");
        sb.AppendLine("|----------|------------------------------|");
        foreach (var q in report.QueryFingerprints.OrderBy(x => x.QueryId, StringComparer.OrdinalIgnoreCase))
        {
            sb.Append('|').Append(MdCell(q.QueryId)).Append('|').Append(MdCell(q.Fingerprint)).AppendLine("|");
        }
        sb.AppendLine();

        EmitActionItems(sb, report);

        sb.AppendLine("## Complete findings by rule");
        sb.AppendLine();
        sb.AppendLine("*Includes PASS rows for audit trail. Prefer **Action items** section for daily triage.*");
        sb.AppendLine();

        foreach (var ruleId in report.ByRule.Select(b => b.RuleId))
        {
            var items = report.Findings
                .Where(f => string.Equals(f.RuleId, ruleId, StringComparison.OrdinalIgnoreCase))
                .OrderBy(FindingSeverityRank)
                .ThenBy(f => f.Message, StringComparer.OrdinalIgnoreCase)
                .ToList();
            if (items.Count == 0)
                continue;

            sb.AppendLine($"### `{MdEscape(ruleId)}`");
            sb.AppendLine();
            var idx = 0;
            foreach (var f in items)
            {
                idx++;
                EmitFinding(sb, idx, f);
                sb.AppendLine();
            }
        }

        sb.AppendLine("---");
        sb.AppendLine($"*Generated by sqltool **plan** command. Report UTC: {MdEscape(report.GeneratedAtUtc)}*");
        sb.AppendLine();
    }

    private static void EmitRunSummary(StringBuilder sb, Phase3PlansReport report)
    {
        sb.AppendLine("## Run summary");
        sb.AppendLine();
        sb.AppendLine("| | |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Environment | {MdCell(report.Environment)} |");
        sb.AppendLine($"| Generated (UTC) | {MdCell(report.GeneratedAtUtc)} |");
        sb.AppendLine($"| Started (UTC) | {MdCell(report.StartedAtUtc)} |");
        sb.AppendLine($"| Duration | {MdCell($"{report.DurationMs} ms")} |");
        sb.AppendLine($"| Connection | {MdCell(report.ConnectionSummary)} |");
        sb.AppendLine($"| Queries in scope | {MdCell(report.QueryCount.ToString())} |");
        sb.AppendLine($"| Rule checks (rows in findings) | {MdCell($"{report.TotalRules} rules / {report.TotalFindings} findings")} |");
        sb.AppendLine();
    }

    private static void EmitRulesAtAGlance(StringBuilder sb, Phase3PlansReport report)
    {
        sb.AppendLine("## Rules — pass / warn / fail / error counts");
        sb.AppendLine();
        sb.AppendLine("| Rule ID | Pass | Warn | Fail | Error |");
        sb.AppendLine("|---------|-----:|-----:|-----:|------:|");
        foreach (var row in report.ByRule)
        {
            sb.Append("| `").Append(MdEscape(row.RuleId)).Append("` | ");
            sb.Append(row.Pass).Append(" | ").Append(row.Warn).Append(" | ");
            sb.Append(row.Fail).Append(" | ").Append(row.Error).AppendLine(" |");
        }
        sb.AppendLine();
    }

    private static void EmitActionItems(StringBuilder sb, Phase3PlansReport report)
    {
        var action = report.Findings
            .Where(f =>
                string.Equals(f.Status, "fail", StringComparison.OrdinalIgnoreCase)
                || string.Equals(f.Status, "error", StringComparison.OrdinalIgnoreCase)
                || string.Equals(f.Status, "warn", StringComparison.OrdinalIgnoreCase))
            .OrderBy(FindingSeverityRank)
            .ThenBy(f => f.RuleId, StringComparer.OrdinalIgnoreCase)
            .ThenBy(f => f.Message, StringComparer.OrdinalIgnoreCase)
            .ToList();

        sb.AppendLine("## Action items (FAIL, ERROR, and WARN only)");
        sb.AppendLine();

        if (action.Count == 0)
        {
            sb.AppendLine("*No failures or warnings reported for this run.*");
            sb.AppendLine();
            return;
        }

        var n = 0;
        foreach (var f in action)
        {
            n++;
            sb.AppendLine($"### {n}. `{MdEscape(f.RuleId)}` — **{MdEscape(f.Status.ToUpperInvariant())}**");
            EmitFindingBody(sb, f);
            sb.AppendLine();
        }
    }

    private static void EmitFinding(StringBuilder sb, int ordinal, Phase3RuleFinding f)
    {
        sb.AppendLine($"#### {ordinal}. **{MdEscape(f.Status.ToUpperInvariant())}** ({MdEscape(f.Severity)})");
        EmitFindingBody(sb, f);
    }

    private static void EmitFindingBody(StringBuilder sb, Phase3RuleFinding f)
    {
        sb.AppendLine($"- **Message:** {MdParagraph(f.Message)}");
        if (!string.IsNullOrWhiteSpace(f.Recommendation))
            sb.AppendLine($"- **Suggestion:** {MdParagraph(f.Recommendation)}");
        if (f.AffectedObjects.Count > 0)
            sb.AppendLine($"- **Affected objects:** `{string.Join("`, `", f.AffectedObjects.Select(MdEscape))}`");
        if (f.QueryIds.Count > 0)
            sb.AppendLine($"- **Related query IDs:** {string.Join(", ", f.QueryIds.Select(q => $"`{MdEscape(q)}`"))}");

        if (FormatEvidenceJson(f.Evidence) is { } ej)
        {
            sb.AppendLine("- **Evidence:**");
            sb.AppendLine();
            sb.AppendLine("```json");
            sb.AppendLine(ej);
            sb.AppendLine("```");
        }
    }

    private static string? FormatEvidenceJson(IReadOnlyDictionary<string, object?>? evidence)
    {
        if (evidence is null || evidence.Count == 0)
            return null;
        try
        {
            return JsonSerializer.Serialize(evidence, EvidenceJsonOptions);
        }
        catch
        {
            return "{ \"_note\": \"evidence could not be serialized to JSON\" }";
        }
    }

    private static readonly JsonSerializerOptions EvidenceJsonOptions = new() { WriteIndented = true };

    private static int FindingSeverityRank(Phase3RuleFinding f)
    {
        if (string.Equals(f.Status, "fail", StringComparison.OrdinalIgnoreCase)
            || string.Equals(f.Status, "error", StringComparison.OrdinalIgnoreCase))
            return 0;
        if (string.Equals(f.Status, "warn", StringComparison.OrdinalIgnoreCase))
            return 1;
        return 2;
    }

    /// <summary>One line for tables; collapse newlines.</summary>
    private static string MdCell(string? text)
    {
        if (string.IsNullOrEmpty(text))
            return "";
        var one = text.Replace("\r\n", " ").Replace('\n', ' ').Trim();
        return MdEscape(one);
    }

    /// <summary>Single-line for list items; collapse internal line breaks.</summary>
    private static string MdParagraph(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return "";
        var t = Regex.Replace(text.Trim(), @"\s+", " ");
        return MdEscape(t);
    }

    /// <summary>Escape characters that break Markdown tables and inline code.</summary>
    private static string MdEscape(string text)
    {
        if (text.Length == 0)
            return text;
        return text.Replace("\\", "\\\\")
            .Replace("|", "\\|");
    }
}
